package io.github.ronaldobertolucci.mtgdeckbuilder.service.deck;

import io.github.ronaldobertolucci.mtgdeckbuilder.dto.card.*;
import io.github.ronaldobertolucci.mtgdeckbuilder.model.deck.*;
import io.github.ronaldobertolucci.mtgdeckbuilder.service.card.CardIntegrationService;
import java.util.*;
import java.util.stream.Collectors;

/** Works on the locked aggregate; persistence and transaction belong to DeckService. */
final class DeckAccessoryService {
    private final CardIntegrationService integration;

    DeckAccessoryService(CardIntegrationService integration) { this.integration = integration; }

    static boolean generatesAccessories(BoardType board) {
        return board == BoardType.MAINBOARD || board == BoardType.COMMANDER
                || board == BoardType.SIDEBOARD || board == BoardType.COMPANION;
    }

    void addAccessories(Deck deck, Collection<CardDetailsResponse> sources) {
        var existing = deck.getCards().stream().filter(c -> c.getBoardType() == BoardType.TOKENS)
                .map(DeckCard::getOracleId).collect(Collectors.toSet());
        for (UUID id : accessories(sources)) {
            if (existing.add(id)) deck.addCard(DeckCard.generatedToken(id));
        }
    }

    void removeOrphans(Deck deck, DeckCard removed) {
        if (!generatesAccessories(removed.getBoardType())) return;
        var automatic = deck.getCards().stream()
                .filter(c -> c.getBoardType() == BoardType.TOKENS && c.isAutoGenerated()).toList();
        if (automatic.isEmpty()) return;
        var candidates = accessories(List.of(integration.fetchCardDetails(removed.getOracleId())));
        var removable = automatic.stream().filter(c -> candidates.contains(c.getOracleId())).toList();
        if (removable.isEmpty()) return;
        var remaining = deck.getCards().stream().filter(c -> generatesAccessories(c.getBoardType()))
                .map(DeckCard::getOracleId).distinct().map(integration::fetchCardDetails).toList();
        var referenced = accessories(remaining);
        removable.stream().filter(c -> !referenced.contains(c.getOracleId())).forEach(deck::removeCard);
    }

    private Set<UUID> accessories(Collection<CardDetailsResponse> sources) {
        var ids = sources.stream().flatMap(c -> c.allParts().stream()).map(RelatedCard::id)
                .collect(Collectors.toCollection(LinkedHashSet::new));
        if (ids.isEmpty()) return Set.of();
        return integration.resolveCards(ids).stream().filter(ResolvedCardResponse::isAccessory)
                .map(ResolvedCardResponse::oracleId).collect(Collectors.toSet());
    }
}
