package io.github.ronaldobertolucci.mtgdeckbuilder.service.deck;

import io.github.ronaldobertolucci.mtgdeckbuilder.dto.card.*;
import io.github.ronaldobertolucci.mtgdeckbuilder.dto.deck.*;
import io.github.ronaldobertolucci.mtgdeckbuilder.exception.RuleErrorCode;
import io.github.ronaldobertolucci.mtgdeckbuilder.exception.RuleViolationException;
import io.github.ronaldobertolucci.mtgdeckbuilder.model.deck.*;
import io.github.ronaldobertolucci.mtgdeckbuilder.repository.DeckRepository;
import io.github.ronaldobertolucci.mtgdeckbuilder.service.card.*;
import io.github.ronaldobertolucci.mtgdeckbuilder.service.deck.validation.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import java.util.*;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;
import static io.github.ronaldobertolucci.mtgdeckbuilder.config.CardTestFixtures.legalities;

@ExtendWith(MockitoExtension.class)
class DeckAccessoriesTest {
    @Mock DeckRepository repository;
    @Mock CardIntegrationService integration;
    DeckService service;
    Deck deck = new Deck(42L, "Accessories", Format.MODERN);
    UUID deckId = UUID.randomUUID(), source = UUID.randomUUID(), printing = UUID.randomUUID(), token = UUID.randomUUID();

    @BeforeEach void setup() {
        var rules = new CardRuleOverrideService();
        service = new DeckService(repository, integration,
                List.of(new Constructed60Validator(rules), new CommanderValidator(rules, integration)), new DeckImportParserService());
    }
    CardDetailsResponse details(UUID id, UUID... parts) {
        return new CardDetailsResponse(id, "Source", "Legendary Creature", "", List.of(), legalities(), List.of(),
                2.0, "{2}", "rare", List.of(), "normal", Arrays.stream(parts).map(RelatedCard::new).toList());
    }
    ResolvedCardResponse resolved(UUID id, UUID oracle, String layout, String type) {
        return new ResolvedCardResponse(id, oracle, "Related", layout, type);
    }
    void owned() {
        when(repository.findOwnedForUpdate(deckId, 42L)).thenReturn(Optional.of(deck));
        when(repository.saveAndFlush(any())).thenAnswer(i -> i.getArgument(0));
    }
    void resolveToken() {
        when(integration.resolveCards(Set.of(printing))).thenReturn(List.of(resolved(printing, token, "token", "Token Creature")));
    }
    DeckResponse upsert(UUID id, BoardType board, int quantity) {
        return service.upsertCard(42L, deckId, new UpsertDeckCardRequest(id, board, quantity));
    }
    @Test void filtersAccessoriesAndDeduplicatesPrintingsAndParts() {
        owned();
        var p2 = UUID.randomUUID(); var p3 = UUID.randomUUID(); var p4 = UUID.randomUUID(); var p5 = UUID.randomUUID();
        when(integration.fetchCardDetails(source)).thenReturn(details(source, printing, printing, p2, p3, p4, p5));
        when(integration.resolveCards(Set.of(printing,p2,p3,p4,p5))).thenReturn(List.of(
                resolved(printing, token, "token", "Token Creature"), resolved(p2, token, "double_faced_token", "Token"),
                resolved(p3, UUID.randomUUID(), "emblem", "Emblem"), resolved(p4, UUID.randomUUID(), "normal", "Dungeon"),
                resolved(p5, source, "normal", "Legendary Creature")));
        var response = upsert(source, BoardType.MAINBOARD, 3);
        assertThat(response.cards()).hasSize(4);
        assertThat(response.cards().stream().filter(c -> c.boardType() == BoardType.TOKENS))
                .allSatisfy(c -> { assertThat(c.quantity()).isOne(); assertThat(c.isAutoGenerated()).isTrue(); });
    }
    @Test void existingManualTokenIsNotChangedAndNeverRemoved() {
        owned(); resolveToken();
        when(integration.fetchCardDetails(source)).thenReturn(details(source, printing));
        var manual = new DeckCard(token, 12, BoardType.TOKENS); deck.addCard(manual);
        upsert(source, BoardType.MAINBOARD, 1);
        upsert(source, BoardType.MAINBOARD, 0);
        assertThat(deck.getCards()).containsExactly(manual);
        assertThat(manual.getQuantity()).isEqualTo(12);
        assertThat(manual.isAutoGenerated()).isFalse();
        verify(integration).resolveCards(any());
    }
    @Test void quantityEditsKeepOriginAndRemovalDeletesEditedAutomaticToken() {
        owned(); resolveToken();
        when(integration.fetchCardDetails(source)).thenReturn(details(source, printing));
        when(integration.fetchCardDetails(token)).thenReturn(new CardDetailsResponse(token,"Token","Token Creature","",List.of(),Map.of(),List.of(),null,null,null,List.of(),"token",List.of()));
        upsert(source, BoardType.MAINBOARD, 4);
        var edited = upsert(token, BoardType.TOKENS, 12).cards().stream().filter(c -> c.oracleId().equals(token)).findFirst().orElseThrow();
        assertThat(edited.isAutoGenerated()).isTrue(); assertThat(edited.quantity()).isEqualTo(12);
        upsert(source, BoardType.MAINBOARD, 1);
        verify(integration).resolveCards(any());
        upsert(source, BoardType.MAINBOARD, 0);
        assertThat(deck.getCards()).isEmpty();
    }
    @Test void sharedOracleAcrossDifferentPrintingsRetainsTokenUntilLastSource() {
        owned(); var other = UUID.randomUUID(); var otherPrinting = UUID.randomUUID();
        deck.addCard(new DeckCard(source, 1, BoardType.MAINBOARD));
        deck.addCard(new DeckCard(other, 1, BoardType.MAINBOARD));
        deck.addCard(DeckCard.generatedToken(token));
        when(integration.fetchCardDetails(source)).thenReturn(details(source, printing));
        when(integration.fetchCardDetails(other)).thenReturn(details(other, otherPrinting));
        resolveToken();
        when(integration.resolveCards(Set.of(otherPrinting))).thenReturn(List.of(resolved(otherPrinting, token, "token", "Token")));
        upsert(source, BoardType.MAINBOARD, 0);
        assertThat(deck.getCards()).extracting(DeckCard::getOracleId).containsExactly(other, token);
        upsert(other, BoardType.MAINBOARD, 0);
        assertThat(deck.getCards()).isEmpty();
    }
    @org.junit.jupiter.params.ParameterizedTest
    @org.junit.jupiter.params.provider.EnumSource(value = BoardType.class, names = {"SIDEBOARD", "COMPANION"})
    void additionalZonesGenerateAndKeepSharedTokensUntilLastSourceRemoved(BoardType board) {
        owned(); resolveToken();
        var sourceDetails = details(source, printing);
        when(integration.fetchCardDetails(source)).thenReturn(new CardDetailsResponse(source, "Source", "Creature", "",
                List.of(), legalities(), List.of("Companion"), null, null, null, List.of(), "normal", sourceDetails.allParts()));
        upsert(source, board, 1);
        assertThat(deck.getCards()).anySatisfy(card -> {
            assertThat(card.getOracleId()).isEqualTo(token); assertThat(card.isAutoGenerated()).isTrue();
        });
        upsert(source, BoardType.MAINBOARD, 1);
        upsert(source, BoardType.MAINBOARD, 0);
        assertThat(deck.getCards()).extracting(DeckCard::getBoardType).containsExactly(board, BoardType.TOKENS);
        upsert(source, board, 0);
        assertThat(deck.getCards()).isEmpty();
        // Reverse removal order: MAINBOARD must also retain a token generated by an external zone.
        upsert(source, board, 1);
        upsert(source, BoardType.MAINBOARD, 1);
        upsert(source, board, 0);
        assertThat(deck.getCards()).anySatisfy(card -> assertThat(card.getOracleId()).isEqualTo(token));
        upsert(source, BoardType.MAINBOARD, 0);
        assertThat(deck.getCards()).isEmpty();
    }

    @org.junit.jupiter.params.ParameterizedTest
    @org.junit.jupiter.params.provider.EnumSource(value = BoardType.class, names = {"SIDEBOARD", "COMPANION"})
    void importGeneratesAccessoriesFromAdditionalZones(BoardType board) {
        when(repository.saveAndFlush(any())).thenAnswer(i -> i.getArgument(0)); resolveToken();
        when(integration.fetchCardDetailsByName("Source")).thenReturn(new CardDetailsResponse(source, "Source", "Creature", "",
                List.of(), legalities(), List.of("Companion"), null, null, null, List.of(), "normal", List.of(new RelatedCard(printing))));
        var result = service.importDeck(42L, new ImportDeckRequest("Imported", Format.MODERN, board.name() + "\n1 Source"));
        assertThat(result.cards()).hasSize(2).anySatisfy(card -> {
            assertThat(card.oracleId()).isEqualTo(token); assertThat(card.isAutoGenerated()).isTrue();
        });
    }

    @Test void commanderCreationGeneratesAccessoriesAndTokensDoNotBlockLastCommanderRemoval() {
        owned(); deck.setFormat(Format.COMMANDER); resolveToken();
        when(integration.fetchCardDetails(source)).thenReturn(details(source, printing));
        var created = service.create(42L, new CreateDeckRequest("Leader", Format.COMMANDER, List.of(source)));
        assertThat(created.cards()).hasSize(2);
        deck.addCard(new DeckCard(source, 1, BoardType.COMMANDER)); deck.addCard(DeckCard.generatedToken(token));
        upsert(source, BoardType.COMMANDER, 0);
        assertThat(deck.getCards()).isEmpty();
    }
    @Test void sameOracleRemainingInCommanderStillReferencesToken() {
        owned(); resolveToken();
        when(integration.fetchCardDetails(source)).thenReturn(details(source, printing));
        deck.addCard(new DeckCard(source, 1, BoardType.MAINBOARD));
        deck.addCard(new DeckCard(source, 1, BoardType.COMMANDER));
        deck.addCard(DeckCard.generatedToken(token));
        upsert(source, BoardType.MAINBOARD, 0);
        assertThat(deck.getCards()).extracting(DeckCard::getBoardType).containsExactly(BoardType.COMMANDER, BoardType.TOKENS);
    }

    @Test void addingAnotherSourcePreservesEditedAutomaticToken() {
        owned(); resolveToken();
        when(integration.fetchCardDetails(source)).thenReturn(details(source, printing));
        var automatic = DeckCard.generatedToken(token); automatic.setQuantity(12); deck.addCard(automatic);
        upsert(source, BoardType.MAINBOARD, 1);
        assertThat(automatic.getQuantity()).isEqualTo(12);
        assertThat(automatic.isAutoGenerated()).isTrue();
        assertThat(deck.getCards()).hasSize(2);
    }

    @Test void importBatchesSourcesAndGeneratesAutomaticTokens() {
        when(repository.saveAndFlush(any())).thenAnswer(i -> i.getArgument(0)); resolveToken();
        when(integration.fetchCardDetailsByName("Source")).thenReturn(details(source, printing));
        var response = service.importDeck(42L, new ImportDeckRequest("Imported", Format.MODERN,"1 Source\n1 Source"));
        assertThat(response.cards()).hasSize(2);
        assertThat(response.cards().stream().filter(c -> c.boardType() == BoardType.MAINBOARD).findFirst().orElseThrow()
                .quantity()).isEqualTo(2);
        assertThat(response.cards().stream().filter(c -> c.boardType() == BoardType.TOKENS).findFirst().orElseThrow())
                .satisfies(c -> { assertThat(c.quantity()).isOne(); assertThat(c.isAutoGenerated()).isTrue(); });
        verify(integration).resolveCards(Set.of(printing));
    }

    @Test void tokenZoneImportDoesNotSaveDeckOrLookUpCards() {
        assertThatThrownBy(() -> service.importDeck(42L,
                new ImportDeckRequest("Rejected", Format.MODERN, "1 Source\nTokens\n12 Token")))
                .isInstanceOfSatisfying(RuleViolationException.class,
                        ex -> assertThat(ex.getCode()).isEqualTo(RuleErrorCode.IMPORT_TOKENS_NOT_SUPPORTED));
        verifyNoInteractions(repository, integration);
    }
}
