package io.github.ronaldobertolucci.mtgdeckbuilder.exception;

public enum RuleErrorCode {
    IMPORT_TEXT_REQUIRED,
    IMPORT_NO_CARDS,
    IMPORT_INVALID_LINE,
    IMPORT_INVALID_QUANTITY,
    INVALID_COMMANDER_SELECTION,
    COMMANDER_NOT_ELIGIBLE,
    INCOMPATIBLE_COMMANDER_PAIR,
    CARD_BANNED,
    CARD_NOT_LEGAL,
    CARD_LEGALITY_UNKNOWN,
    COMMANDER_DATA_INCOMPLETE,
    COLOR_IDENTITY_UNKNOWN,
    COPY_LIMIT_EXCEEDED,
    COLOR_IDENTITY_INCOMPATIBLE,
    COMMANDER_SIZE_LIMIT_EXCEEDED,
    SIDEBOARD_SIZE_LIMIT_EXCEEDED,
    INVALID_COMPANION_QUANTITY,
    COMPANION_NOT_ELIGIBLE,
    COMPANION_LIMIT_EXCEEDED,
    LAST_COMMANDER_REQUIRED,
    BOARD_TYPE_NOT_SUPPORTED,
    CARD_NOT_ACCESSORY
}
